openapi: 3.0.3
info:
  title: Gallery API
  version: 1.0.1
paths:
  /hello:
    get:
      summary: Returns a greeting from the gallery
      operationId: hello
      responses:
        '200':
          description: Successful response
          content:
            text/plain:
              schema:
                type: string